### ISSUE TITLE
Cleanup integer param types in rust API wrapper

### ISSUE THREAD

**Issue by swiftcoder** [gfx-rs/wgpu-rs#116]
At the moment API parameters are a bit all-over-the-map when it comes to the integral types they take, and it makes working with the API just that little bit higher friction.

For example, `create_buffer_mapped()` wants a usize count parameter, but `create_buffer()` takes a u64 buffer size (by way of the BufferAddress type), while most other integral parameters are u32.

It would simplify API usage a lot if we standardised on usize for anything that is either a memory address or an array length, since most rust standard library functionality expects that (i.e. I'd love not to have to cast the result of std::mem::size_of() every time)

**Comment by kvark** [comment]
I have a slight preference towards 1:1 correspondence of types with upstream API, where possible. As such, buffer offsets are by design specified as `u64`. This also matches the way `gfx-hal` exposes these offsets.

That is to say, if we identify a few concrete places where we can trade this for better ergonomics, I'd be happy to consider them. Perhaps, you could post more specific examples, and propose changes to the API, so that we can see how they would improve the cases?

**Comment by swiftcoder** [comment]
> As such, buffer offsets are by design specified as u64

I can't bring to mind any examples where usize buffer offsets would cause a problem. There aren't that many 32-bit systems left in the world, let alone ones with > 4GB of graphics memory.

> Perhaps, you could post more specific examples, and propose changes to the API, so that we can see how they would improve the cases?

The highest value, to my mind, would be to convert `create_buffer` and `copy_buffer_to_buffer` to take usize parameters. Right now I have a variation on `std::mem::size_of::<UniformBufferLayout>() as u64` at every single call point for both of those functions.

```
    /// Creates a new buffer.
    pub fn create_buffer(&self, size: usize, usage: BufferUsage) -> Buffer {
        Buffer {
            id: wgn::wgpu_device_create_buffer(
                self.id,
                &wgn::BufferDescriptor {
                    size: size as u64,
                    usage,
                },
            ),
        }
    }
```

```
    /// Copy data from one buffer to another.
    pub fn copy_buffer_to_buffer(
        &mut self,
        source: &Buffer,
        source_offset: usize,
        destination: &Buffer,
        destination_offset: usize,
        copy_size: usize,
    ) {
        wgn::wgpu_command_encoder_copy_buffer_to_buffer(
            self.id,
            source.id,
            source_offset as u64,
            destination.id,
            destination_offset as u64,
            copy_size as u64,
        );
    }
```

**Comment by kvark** [comment]
If we change the buffer size/offset to a different type, we have to do it consistently. For example, we can't change BufferDescriptor](https://github.com/gfx-rs/wgpu/blob/951641dcc50b355eda894c9a5cd6da057d48765b/wgpu-native/src/resource.rs#L55) in wgpu-native (since it has to be `repr(C)` and matching the upstream), we'd have to basically duplicate it (and other structs) in wgpu-rs. We already do that for some, but this change would mean more duplication. Also cc @grovesNL who is moving the structs out into a separate crate.

**Comment by swiftcoder** [comment]
Yes, that's largely why I removed BufferDescriptor from the wrapper API entirely in the example. 

Particularly for a simple function like `create_buffer`, I'm not sure it's buying us much to expose the descriptor type in the API (and it's noticeable that `create_buffer_mapped`, which doesn't expose the descriptor, is simpler to use).

**Comment by DethRaid** [comment]
As someone who just started using `wgpu-rs`, I agree that `create_buffer_mapped` and `create_buffer` using different types for the buffer sizes is a bit weird. I would expect there to be one type that represents the size of a buffer, and that type to be used throughout the API

I don't have a strong opinion on what that type should be. I agree that matching the types of the underlying native API makes sense, even if it causes a few more casts in Rust-land

**Comment by kvark** [comment]
There is no `create_buffer_mapped` any more 🎉
