### ISSUE TITLE
Panic when no adapters are available

### ISSUE THREAD

**Issue by parasyte** [gfx-rs/wgpu-rs#117]
Similar to #105 
Originally reported in https://github.com/parasyte/pixels/issues/36

We try to catch any errors from `wgpu::Adapter::request` to provide a "helpful" error message, but our error handler never gets called: https://github.com/parasyte/pixels/blob/98983d201db0639f51c264ade5cf876f8df65d1e/src/lib.rs#L412-L413

The backtrace points to the panic occurring here in `wgpu-native`: https://github.com/gfx-rs/wgpu/blob/951641dcc50b355eda894c9a5cd6da057d48765b/wgpu-native/src/instance.rs#L473-L475

The `wgpu::Adapter::request` method itself is suspicious. The docs claim it returns `None` when an adapter cannot be found, but it is clearly hardcoded to return `Some<T>`: https://github.com/gfx-rs/wgpu-rs/blob/cbdd74fb408d87c04423bd375806b3b6c1be1bb0/src/lib.rs#L538-L547

Given these two issues, we're unable to capture the error (transform the `None` into `Result<_, E>`) because this method never returns `None`. I would work on this, but unfortunately I don't know the best way to approach the `extern "C"` interface. Should it just return `Option<AdapterId>`?

**Comment by zserik** [comment]
Actually, the unwrap lies in rust code here: 

https://github.com/gfx-rs/wgpu/blob/c33b1e81fddf480f24e543cd3689b8991029d893/wgpu-native/src/instance.rs#L473

**Comment by grovesNL** [comment]
> It would be a good idea to call `request_adapter` directly.

In general we should avoid skipping the C API for functional changes like this, since we also want to allow other languages using the C API to fail gracefully too.

> I would work on this, but unfortunately I don't know the best way to approach the `extern "C"` interface. Should it just return `Option<AdapterId>`?

We can't return `Option<AdapterId>` in the C API because we don't have `Option` available in C, but we need to be able to use the return value there.

We haven't implemented [full WebGPU error handling](https://github.com/gpuweb/gpuweb/blob/master/design/ErrorHandling.md) yet, so for now the C API could use the special `Id::ERROR` for `None` and check for this in wgpu-rs. This is similar to the following check which we already have for swapchain errors: https://github.com/gfx-rs/wgpu-rs/blob/cbdd74fb408d87c04423bd375806b3b6c1be1bb0/src/lib.rs#L1358

**Comment by parasyte** [comment]
Duplicate of https://github.com/gfx-rs/wgpu/issues/368
