### ISSUE TITLE
`Texture` API feedback - having a `Texture` keep its descriptor

### ISSUE THREAD

**Issue by mitchmindtree** [gfx-rs/wgpu-rs#205]
I just wanted to share a quick "user experience" anecdote on how `Texture`s are currently handled in nannou in case you might find it interesting!

One very common case I find myself running into when using `Texture`s is needing some information about the `Texture` after I have already created it. E.g. any time I want to create a `BufferCopyView` or `TextureCopyView` for a `Texture`, I need to make sure that I also pipe through all the relevant descriptor information for that `Texture` through my code. The same goes for any occasion where I require the dimensions, sample count or format of a `Texture` long after it has been recreated - I would need to pipe that information through from the moment the `Texture` was created with its descriptor to where I need access to it.

In order to avoid users needing to make custom wrapper types to store this information together or to pipe this information through code by adding extra arguments to many functions, nannou provides its own "wrapper" `Texture` type that stores the `Descriptor` with which the texture was created internally. This allows for providing [a whole suite of useful methods](https://docs.rs/nannou/0.13.1/nannou/wgpu/struct.Texture.html#method.descriptor) on `Texture`. In order to avoid ambiguity, we re-export the wgpu `Texture` type as `TextureHandle`, and provide a `Deref` impl for `Texture` that de-references to the inner `TextureHandle`.

While many of the linked methods are not so relevant to `wgpu` itself, I think many do give an idea of how useful having the `TextureDescriptor` alongside the `Texture` can be downstream. What are your thoughts on the `Texture` type storing and exposing the descriptor with which it was created? Even providing a single `fn descriptor(&self) -> &wgpu::TextureDescriptor` method, would allow nannou to create a `TextureExt` trait to provide the majority of these methods, rather than creating a wrapper type? The potential issue I see with a wrapper type in this situation is that nannou will inevitably create APIs that expect the `Texture` wrapper type, meaning users who only have an inner `wgpu::Texture` instance will not be able to access those APIs as easily. This hasn't turned out to be a problem in practise though.

All that said, this is not really a great problem for nannou, but I thought wgpu devs might find it interesting to consider :)

**Comment by kvark** [comment]
Thank you for feedback!

Generally, graphics API drifted away from an ability to query any properties about objects you create, since ultimately the driver wants to keep it in a different form than what you pass in, and you always have the data to begin with.

Speaking practically, we could store descriptors for some of the objects: we have the luxury of wrappers inside wgpu-rs, and we pass everything by reference anyway. However, we can't have it *consistently*. For example, some descriptors have references in them (`BindGroupLayoutDescriptor`), which aren't storeable. So my preference would be to only start doing this if we can roll this out consistently for all objects, not selectively.

**Comment by kvark** [comment]
This is discussed upstream in https://github.com/gpuweb/gpuweb/issues/1498
