### ISSUE TITLE
Consume command buffers on `submit`

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu-rs#267]
This would reflect the semantics of the API. You can't re-use them anyway.

**Comment by shika-blyat** [comment]
The submit functions takes a slice, which allows people to do things like:
```rust
            let encoder = encoder.finish();
            let cb = [encoder];
            state.queue.submit(&cb);
            // here encoder remains in the scope
```
one way to avoid this would be to take a `Vec<CommandEncoder>` instead of `&[CommandEncoder]`, right ? 
The main downside of a such thing would be that it enforces people using a Vec, and would be a breaking change :thinking:. 
Were you thinking about something else or is this this what you're expecting ?

**Comment by kvark** [comment]
I'm looking into it, will accept `IntoIterator<Item = CommandBuffer>`
