### ISSUE TITLE
Compiler errors when building project with wgpu-rs dependency

### ISSUE THREAD

**Issue by rukai** [gfx-rs/wgpu-rs#279]
I don't know what is expected of the project at the moment, but figured I would report it anyway.

You should be able to reproduce by cloning this repo and running this script:
https://github.com/rukai/brawllib_rs/blob/master/examples/run_web_visualiser.sh

![image](https://user-images.githubusercontent.com/5120858/80266944-0605dd80-86e2-11ea-948d-a861c372a3da.png)

**Comment by grovesNL** [comment]
For the web backend you currently need to pass `RUSTFLAGS=--cfg=web_sys_unstable_apis` because the WebGPU API is unstable (it's hidden behind a flag in wasm_bindgen, e.g. https://github.com/rustwasm/wasm-bindgen/blob/fc86589715996bfea5101f2b57493fb2055b0efd/crates/web-sys/src/features/gen_GpuBufferUsage.rs#L4)

**Comment by rukai** [comment]
https://github.com/rukai/brawllib_rs/blob/88e466175e9236875f62ca7aae25b070d8708e35/examples/run_web_visualiser.sh#L7 I think I'm already doing that here right?

**Comment by grovesNL** [comment]
Oh sorry, I missed that and just noticed the compiler errors complaining about missing functions.

In that case it's probably breaking because of these patches https://github.com/gfx-rs/wgpu-rs/blob/master/Cargo.toml#L75 (it looks like a slightly older version of wasm-bindgen is being used than the one we need for WebGPU).

Could you try patching wasm-bindgen in your project in the same way to use the latest `master`? The patches are temporary until there's a new wasm-bindgen release available.

**Comment by rukai** [comment]
Yes that fixes it, I made https://github.com/gfx-rs/wgpu-rs/pull/280 to document this required workaround.
