### ISSUE TITLE
Index buffer with mapped_at_creation=true results in corrupt contents

### ISSUE THREAD

**Issue by fintelia** [gfx-rs/wgpu-rs#436]
When I attempt to create an index buffer with mapped_at_creation set, the initial values I try to load into the buffer seem to be ignored, and the buffer contents are just garbage instead (as seen via RenderDoc or the rendered output). The code I'm using is based on similar logic that relied on the old create_buffer_mapped interface:
```rust
let make_index_buffer = |resolution: u16| -> wgpu::Buffer {
    let buffer = device.create_buffer(&wgpu::BufferDescriptor {
        size: 12 * (resolution as u64 + 1) * (resolution as u64 + 1),
        usage: wgpu::BufferUsage::INDEX,
        label: Some(&format!("index_buffer_{0}x{0}", resolution)),
        mapped_at_creation: true,
    });
    {
        let mut buffer_view = buffer.slice(..).get_mapped_range_mut();
        let data: &mut [u16] = bytemuck::cast_slice_mut(&mut *buffer_view);

        let mut i = 0;
        let width = resolution + 1;
        for y in 0..resolution {
            for x in 0..resolution {
                for offset in [0, 1, width, 1, width + 1, width].iter() {
                    data[i] = offset + (x + y * width);
                    i += 1;
                }
            }
        }
    }
    buffer
};
```

I was [able to work around this](https://github.com/fintelia/terra/blob/ed1ffc9ce244846810cbdba3b90f294453b7b3be/src/terrain/quadtree/mod.rs#L50) using a dedicated upload buffer and copying the contents to the index buffer.

I'm running Ubuntu 20.04 with an Radeon RX 580. Please let me know if there are particular traces that would be helpful for me to collect.

**Comment by kvark** [comment]
Do you get the same problem when calling `create_with_data` and providing this data in a slice/vector? Internally, it uses `mapped_at_creation` flag in the same way. All of the examples use the same logic for initializing their index buffers, it's supposed to work fine.

**Comment by fintelia** [comment]
Using `create_buffer_with_data` works fine. Am I supposed to be unmapping the buffer somehow?

**Comment by fintelia** [comment]
Actually, would it be possible just to automatically unmap the buffer the first time it is used? The lifetime parameter on BufferViewMut should ensure that there aren't any of them outstanding

**Comment by kvark** [comment]
> figured that the Drop implementation on BufferViewMut was all I needed

You can request multiple different views, and we only transfer the data over on `unmap` for all of them.

> Actually, would it be possible just to automatically unmap the buffer the first time it is used?

That's not what WebGPU upstream does, and I don't think we want to do that either in wgpu-rs. The "first" use is a `submit()` operation, which has no indication that something is going to be magically unmapped. It's just cleaner to require `unmap`, and doing that earlier gives us more time to actually do the transfer operations, if we want to.

> The lifetime parameter on BufferViewMut should ensure that there aren't any of them outstanding

Using a buffer doesn't borrow it mutably. There is no exclusive access here: you can do mapping operations while also recording some commands on a different thread that use the buffer (as long as you unmap before submitting them).

Our action plan for this issue is to have a proper check in place so that you don't get any content corruption.

**Comment by kvark** [comment]
Validation fix is coming in https://github.com/gfx-rs/wgpu/pull/789 , it will be automatically included in wgpu-rs on the next update.
