### ISSUE TITLE
Whats the best way to cache repeated operations?

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [gfx-rs/wgpu-rs#522]
Why I'm asking the question: https://pastebin.com/12kySWdp. TL;DR: I tried something and it didn't work.

Title says it all.

**Comment by grovesNL** [comment]
Hi! :wave: Command buffers aren't reusable, which is why they're consumed during `submit` (e.g. they can't be resubmitted). Usually applications will keep any necessary state around and rerecord command buffers.

Depending on which parts you'd like to reuse, render bundles might also be helpful. There's an example of render bundle reuse in [msaa-line](https://github.com/gfx-rs/wgpu-rs/blob/master/examples/msaa-line/main.rs#L42).

**Comment by JonathanWoollett-Light** [comment]
@grovesNL ` Usually applications will keep any necessary state around and rerecord command buffers` doesn't recreating command buffers result in them needing to be dispatched again which I beleive (may be wrong here) is an expensive communication between the cpu and gpu? 

`which parts you'd like to reuse, render bundles might also be helpful` will definitely look into that, thanks.

**Comment by grovesNL** [comment]
Recording command buffers should be relatively inexpensive, so hopefully it shouldn't be an issue for most applications.

**Comment by grovesNL** [comment]
I think this has been answered – please reopen if it's still not clear
