### ISSUE TITLE
Graphics shaking on window resize

### ISSUE THREAD

**Issue by maitysubhasis** [gfx-rs/wgpu-rs#536]
I shifted the coordinate to 0,0 to the left, top.
Now the drawn graphics are shaking on resize.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16653067/91238483-c2d47d80-e75a-11ea-86a6-833779a84049.gif)

Any idea how to fix it.

It seems when the window is resized the window itself is trying to resize the graphics but on draw call the graphics is drawn again. Thats the reason for the shakiness.

> Without the coordinate shift the shakiness does not occur.

**Comment by cwfitzgerald** [comment]
Is this using DX12 as a backend?

**Comment by maitysubhasis** [comment]
No, mac os.

**Comment by mattmag** [comment]
I see this as well on Win10 with WGPU
https://stackoverflow.com/questions/65947880/window-resize-jitter-using-wgpu-ris-and-winit

**Comment by kvark** [comment]
I believe this is because the window is resized asynchronously from the rendering. So when you resize fast, at some point you window has width 5. Your frame is recorded for the viewport of 5. But by the time it's presented, the window is already of size 6. So `CAMetalLayer` scales the texture up from 5 to 6, and you see that your rectangle changes in size.

I don't know if anything could be done here.

**Comment by mattmag** [comment]
It happens even at slow resize speeds and is particularly distracting when text is involved.
I'll probably have to abandon my evaluation of wgpu-rs if that nothing can be done about it,  which is a bummer because I'm new to graphics programming and learning wgpu-rs has been fun and not too difficult.

![resize-jitter-text](https://user-images.githubusercontent.com/3790261/106553846-3b005580-64e8-11eb-95d7-f863e7cffdf0.gif)

Here is the behavior that I think users would expect
![sublime-resize](https://user-images.githubusercontent.com/3790261/106554866-405e9f80-64ea-11eb-9eb8-5db06d941d17.gif)

Should I start look looking into using gfx-rs directly?

**Comment by kvark** [comment]
Looks like a known problem - https://thume.ca/2019/06/19/glitchless-metal-window-resizing/
I made a patch following the documentation on `presentsWithTransaction` - https://github.com/gfx-rs/gfx/pull/3627
It doesn't work for me. If you want to play with it, either the `make quad` in gfx-rs, or checkout out gfx-rs and uncommenting [these lines](https://github.com/gfx-rs/wgpu-rs/blob/f891e86e87f0733f04a8078f4be8ead2f24551cf/Cargo.toml#L95-L101) would do.

**Comment by kvark** [comment]
Please try https://github.com/gfx-rs/gfx/pull/3627 as an override to latest wgpu
There is also a similar issue - https://github.com/gfx-rs/wgpu/issues/1168

**Comment by cwfitzgerald** [comment]
Closing because there is an existing wgpu issue.
