### ISSUE TITLE
wasm compilation error on crates.io

### ISSUE THREAD

**Issue by memoryleak47** [gfx-rs/wgpu-rs#581]
When web_sys released its version 0.3.45, it introduced a breaking change, causing a compilation error when wgpu was compiled to wasm. This was fixed already, but the patch didn't make it to crates.io yet, it seems.

**Comment by kvark** [comment]
Not sure I understand. We have "=0.3.45" in the manifest, and we build this target on CI with no issues. What's the breakage?

**Comment by memoryleak47** [comment]
Well, not on crates.io
https://docs.rs/crate/wgpu/0.6.0/source/Cargo.toml
version = "0.3.39"

**Comment by kvark** [comment]
It's sort of useless to stick with crates-io releases of wgpu-rs for WASM target at this point. WebGPU is in development, so browsers constantly break existing content. The only way to track this is with branches that we update together with the browsers, i.e. the `gecko` branch we have today.

**Comment by memoryleak47** [comment]
Ah, didn't know that. Thanks! :)

**Comment by grovesNL** [comment]
As mentioned above, we won't bother to yank releases for this because the published crate won't work on wasm yet anyway (even if it does build correctly). For now it's best to use either the `gecko` branch (which aims to match Firefox Nightly as it's updated) or `master` (where some parts are currently working but other parts are unimplemented).

The version will also be pinned for future releases, or at least while the web API is still unstable.
