### ISSUE TITLE
Use &[&TextureView] instead of &[TextureView] in the TextureArray bind group entry

### ISSUE THREAD

**Issue by krupitskas** [gfx-rs/wgpu-rs#588]
Not every user store TextureView's in Vec<TextureView>, someone can store it in the structs, which makes it basically "unmovable" into a slice.
But if we replace it with &[&TextureView], then we can collect a slice of references to pass it, which easier to handle.
Right now a workaround is to create an intermediate view and push it into an intermediate array, which is not great.

**Comment by 98devin** [comment]
Is there anything preventing `TextureView` from just being `Clone` so that it's easier to move around? Many of the wgpu types are slightly harder to use because they restrict cloning (even though as I understand it they are basically just resource handles)...

**Comment by kvark** [comment]
@98devin the ability to `Clone` things as if they are smart pointers has been considered times and times again. My concern about going this way is that it leaves no way back. It forces the implementation to refcount the objects in a specific way. So far, I don't think the case is strong enough to force this.

**Comment by 98devin** [comment]
@kvark That makes sense. I figured that the limitation was there so that the API or implementation weren't locked into that choice while it's still developing rapidly. I think changing to the `&[&TextureView]` array of references for bind groups is then pretty important. Looking at the code which consumes that enum, I don't think it requires any change, so it would just be an interface update.
