### ISSUE TITLE
Enable mapping buffers via Encoder

### ISSUE THREAD

**Issue by fintelia** [gfx-rs/wgpu-rs#694]
Currently if you want to download a GPU resource produced while rendering a scene, you have to do the following steps in order:

1. Record a buffer copy command onto an active CommandEncoder
2. Finish any other rendering commands and submit the CommandEncoder
3. Call BufferSlice::map_async
4. Poll until the future completes

Because steps (1) and (2) can happen in very different parts of the code, it would be nice if I could run them in (1), (3), (2) order so that the buffer copy and asynchronous buffer map request could happen together. Unfortunately, this reordering doesn't work today: the queue submission will panic because it notices that the buffer is already mapped.

What I propose is to add an additional way of mapping buffers via a method on CommandEncoder. Buffer mapping is already asynchronous, but this method could delay the map operation all the way until the prior command recorded to the CommandEncoder had completed (which would be the copy... exactly what we want). Does this make sense / is it feasible to provide?

**Comment by kvark** [comment]
This question should probably be discussed upstream with WebGPU on https://github.com/gpuweb/gpuweb/issues

The problem with "encoding" a buffer map is that it's not an operation that can be encoded. I.e. when encoding you say you want to do A, B, and C. If B happens to be "map buffer", then what happens if "C" uses the buffer?

Another problem is that it would no longer be visible to the user when the client state of a "Buffer" changes it to become mapped. I.e. the user will see a `submit` and would have to guess which buffers are unavailable for further submissions after that one, if they are mapped. This is worse than just seeing `buffer.map_async()`, which clearly shows that this buffer will be unavailable untilt it's unmapped.

**Comment by fintelia** [comment]
Thinking about this some more, I guess what I really want is `Queue::{read_buffer, read_texture}` functions to mirror the existing write versions of those. That would solve the concern of only seeing a `Queue::submit` call, and would be much less ambiguous about how it interacts with other uses of the buffer/texture.

Do you think this is something that could gain traction upstream? If so I can go ahead and create an issue there.

**Comment by kvark** [comment]
I'd like to see `read_buffer` and `read_texture` being implemented on top of the existing API first, to get a sense of:
  1. whether this is sufficient? in this case it could live in `utils` module, and we are happy
  2. whether there would be need to upstream this to WebGPU
