### ISSUE TITLE
hello-triangle example compiled for WASM panics

### ISSUE THREAD

**Issue by ntroast** [gfx-rs/wgpu-rs#731]
OS: Windows 10 Version 20H2 (OS Build 19042.631)
Browser: Google Chrome Version 90.0.4400.0 (Official Build) canary (64-bit)

I followed the instructions to compile the hello-triangle example for WASM
https://github.com/gfx-rs/wgpu-rs/wiki/Running-on-the-Web-with-WebGPU-and-WebGL

Here is the panic I observed
`hello-triangle.js:322 panicked at 'WGSL is not yet supported by the Web backend', src/backend/web.rs:1060:38`

Please see the console log for details
[localhost-1611789386151.log](https://github.com/gfx-rs/wgpu-rs/files/5883732/localhost-1611789386151.log)

**Comment by grovesNL** [comment]
Hi! 👋  Thanks for reporting the issue!

We're currently moving our examples to use WGSL (WebGPU Shading Language) instead of SPIR-V, but WGSL isn't supported on the wasm backend yet. I think [hello-triangle is the only one that has been converted on `master` so far](https://github.com/gfx-rs/wgpu-rs/pull/669/files#diff-9b85b62efa1f7811f0168570d2ddd299c71690e1a0628933546c9298b23d786cL35-R40), so running the other examples or your own code with SPIR-V should still work.

In the meantime you could do one of the following to get hello-triangle to work locally:
- keep using `master` but load SPIR-V instead of WGSL
- use the [`gecko` branch](https://github.com/gfx-rs/wgpu-rs/tree/gecko/examples) or any commits that still uses SPIR-V
- run examples besides hello-triangle

There's some more context in https://github.com/gfx-rs/wgpu-rs/pull/679#discussion_r563434915

Hopefully this makes sense and we'll try to address this soon.

**Comment by ntroast** [comment]
Thanks for the context, I see you were discussing breaking the other samples :smile:. Also, thank you for the workarounds, and I'm excited to give WGSL a try when its ready!

**Comment by cwfitzgerald** [comment]
Closing due to wgpu-rs -> wgpu migration and due to the likelihood of this being fixed. Please refile if this is still an issue.
