### ISSUE TITLE
Missing Hash and Eq impls for DepthStencilState

### ISSUE THREAD

**Issue by gzp-crey** [gfx-rs/wgpu-rs#769]
Most types implement Eq and Hash. `DepthStencilState` implemented them but after the 0.7 release they are removed.
Could you please add them back.
I'm storing most wgpu resources in a hashmap (for a resource claim based scheduler) and I really miss them. I could implement them manually, but as all the other types implement these trait it seems to be an accidental miss during the API refactors.

**Comment by kvark** [comment]
`DepthStencilState` no longer implements them because now it has `DepthBiasState` inside it with a few floats, and floats don't get the benefit of `Eq` and `Hash`... They previously lived in `RasterizationState`.
I added a few more derives in https://github.com/gfx-rs/wgpu/pull/1227 now. If you need anything else, consider making a PR please!

**Comment by gzp-crey** [comment]
Thanks. I missed the float hashing nature of rust. Now it makes sense that some types don't have a hash by default and I have to craft my own.

**Comment by gzp-crey** [comment]
I thin the issue can can be closed.
