### ISSUE TITLE
Add method to check compatibility between adapter and surface

### ISSUE THREAD

**Issue by OlegOAndreev** [gfx-rs/wgpu-rs#777]
Hi! The `enumerate_adapters` method is very useful for desktop users which can have multiple GPUs since it allows choosing the preferred GPU by name instead of relying on GPU type (integrated/discrete) which I feel is more intuitive.

However, there is one minor problem with choosing the GPU by name: it can potentially be incompatible with the given surface. If I understand correctly, the way to check if the compatibility is calling `Adapter::get_swap_chain_preferred_format` and catching panics.

Maybe a separate method like `Adapter::is_compatible_surface` or `Adapter::try_get_swap_chain_preferred_format` (returning `Result`) could be added?

**Comment by kvark** [comment]
I think `try_get_swap_chain_preferred_format` is a neat idea! Perhaps, returning an error if the surface is incompatible is not the right thing to do though, since it's not an error condition, just something the user would check.
So instead, we could make `get_swap_chain_preferred_format` return a `Result<Option<TextureFormat>, Error>`.

**Comment by OlegOAndreev** [comment]
Sounds great to me! I can prepare a pull-request if it is ok with you.

**Comment by kvark** [comment]
That would be great, thank you!
