### ISSUE TITLE
Building for `gfx-backend-vulkan` without x11

### ISSUE THREAD

**Issue by 0ax1** [gfx-rs/wgpu-rs#90]
Hi!

Currently, wgpu-rs by default enables x11 through wgpu-native when building for `gfx-backend-vulkan`. It'd be great if the x11 feature could be made optional when building wgpu-rs projects.

Removing `features = [x11]` from https://github.com/gfx-rs/wgpu/blob/master/wgpu-native/Cargo.toml#L45 yields a single compile error https://github.com/gfx-rs/wgpu/blob/master/wgpu-native/src/instance.rs#L184 which can be addressed by changing the conditional compilation to `        #[cfg(all(unix, not(target_os = "ios"), not(target_os = "macos"), feature = "x11"))].`

**Comment by kvark** [comment]
That's a bit of a tricky issue. We want wgpu-native to expose all the adapters available on the platform, and the presence of X11 is technically a part of the platform we want to discover. We don't want the clients to enable `x11` feature whenever they target Vulkan. If `x11` is an optional feature that is enabled by default, I don't think Cargo has the support for saying that it will affect `gfx-backend-vulkan` dependency, since this one is limited only to some platforms, i.e. we can't do that:
```toml
[features]
x11 = ["gfx-backend-vulkan/x11"]
```
(because `gfx-backend-vulkan` isn't available everywhere)

**Comment by 0ax1** [comment]
I see, thanks for clarifying that!

**Comment by Diggsey** [comment]
@kvark Couldn't you solve this by adding an extra crate to manage that dependency?

eg. a `gfx-backend-vulkan-x11` crate that compiles on every platform, but only depends on `gfx-backend-vulkan/x11` on platforms that support it. Then, the `x11` feature can enable this intermediate crate.

**Comment by kvark** [comment]
At the end of the day, we are building all the backends available on the platform. We could see this issue as a custom case of trying to reduce this set.

**Comment by kvark** [comment]
I believe this is resolved for Vulkan. Interestingly, there is a similar issue now for GL (which would need to be filed if it's a problem)
